bisect: use selected alternate terms in status output
Alternate bisect terms are helpful when the terms "good" and "bad" are
confusing such as when bisecting for the resolution of an issue (the
first good commit) rather than the introduction of a regression. If
alternate terms are chosen, the terms "good" and "bad" should not be
used in git's output to avoid confusion.

An old/new bisect should end with
$ git bisect old
[sha] is the first new commit

not with
$ git bisect old
[sha] is the first bad commit

Using hardcoded good/bad vocabulary can give confusion about what action
is required:

  status: waiting for bad commit, 1 good commit known
  $ git bisect bad
  error: Invalid command: you're currently in a new/old bisect
  fatal: unknown command: 'bad'

To avoid confusion, use alternate terms consistently across the bisect
output.

Signed-off-by: Jonas Rebmann <kernel@schlaraffenlan.de>
Signed-off-by: Junio C Hamano <gitster@pobox.com>